const displayMappings: Record<string, boolean[][]> = {
	' ': [
		[false, false, false, false, false],
		[false, false, false, false, false],
		[false, false, false, false, false],
		[false, false, false, false, false],
		[false, false, false, false, false],
		[false, false, false, false, false],
		[false, false, false, false, false],
	],
	'0': [
		[false, true, true, true, false],
		[true, false, false, false, true],
		[true, false, false, true, true],
		[true, false, true, false, true],
		[true, true, false, false, true],
		[true, false, false, false, true],
		[false, true, true, true, false],
	],
	'1': [
		[false, false, true, false, false],
		[false, true, true, false, false],
		[false, false, true, false, false],
		[false, false, true, false, false],
		[false, false, true, false, false],
		[false, false, true, false, false],
		[false, true, true, true, false],
	],
	'2': [
		[false, true, true, true, false],
		[true, false, false, false, true],
		[false, false, false, false, true],
		[false, false, false, true, false],
		[false, false, true, false, false],
		[false, true, false, false, false],
		[true, true, true, true, true],
	],
	'3': [
		[false, true, true, true, false],
		[true, false, false, false, true],
		[false, false, false, false, true],
		[false, false, true, true, false],
		[false, false, false, false, true],
		[true, false, false, false, true],
		[false, true, true, true, false],
	],
	'4': [
		[false, false, false, true, false],
		[false, false, true, true, false],
		[false, true, false, true, false],
		[true, false, false, true, false],
		[true, true, true, true, true],
		[false, false, false, true, false],
		[false, false, false, true, false],
	],
	'5': [
		[true, true, true, true, true],
		[true, false, false, false, false],
		[true, true, true, true, false],
		[false, false, false, false, true],
		[false, false, false, false, true],
		[true, false, false, false, true],
		[false, true, true, true, false],
	],
	'6': [
		[false, true, true, true, false],
		[true, false, false, false, true],
		[true, false, false, false, false],
		[true, true, true, true, false],
		[true, false, false, false, true],
		[true, false, false, false, true],
		[false, true, true, true, false],
	],
	'7': [
		[true, true, true, true, true],
		[false, false, false, false, true],
		[false, false, false, true, false],
		[false, false, true, false, false],
		[false, true, false, false, false],
		[false, true, false, false, false],
		[false, true, false, false, false],
	],
	'8': [
		[false, true, true, true, false],
		[true, false, false, false, true],
		[true, false, false, false, true],
		[false, true, true, true, false],
		[true, false, false, false, true],
		[true, false, false, false, true],
		[false, true, true, true, false],
	],
	'9': [
		[false, true, true, true, false],
		[true, false, false, false, true],
		[true, false, false, false, true],
		[false, true, true, true, true],
		[false, false, false, false, true],
		[true, false, false, false, true],
		[false, true, true, true, false],
	],
	'+': [
		[false, false, false, false, false],
		[false, false, true, false, false],
		[false, false, true, false, false],
		[true, true, true, true, true],
		[false, false, true, false, false],
		[false, false, true, false, false],
		[false, false, false, false, false],
	],
	'-': [
		[false, false, false, false, false],
		[false, false, false, false, false],
		[false, false, false, false, false],
		[true, true, true, true, true],
		[false, false, false, false, false],
		[false, false, false, false, false],
		[false, false, false, false, false],
	],
	'*': [
		[false, false, false, false, false],
		[true, false, false, false, true],
		[false, true, false, true, false],
		[false, false, true, false, false],
		[false, true, false, true, false],
		[true, false, false, false, true],
		[false, false, false, false, false],
	],
	'/': [
		[false, false, false, false, false],
		[false, false, false, false, true],
		[false, false, false, true, false],
		[false, false, true, false, false],
		[false, true, false, false, false],
		[true, false, false, false, false],
		[false, false, false, false, false],
	],
	'.': [
		[false, false, false, false, false],
		[false, false, false, false, false],
		[false, false, false, false, false],
		[false, false, false, false, false],
		[false, false, false, false, false],
		[false, true, true, false, false],
		[false, true, true, false, false],
	],
	e: [
		[false, false, false, false, false],
		[false, false, false, false, false],
		[false, true, true, true, false],
		[true, false, false, false, true],
		[true, true, true, true, false],
		[true, false, false, false, false],
		[false, true, true, true, false],
	],
	I: [
		[false, true, true, true, false],
		[false, false, true, false, false],
		[false, false, true, false, false],
		[false, false, true, false, false],
		[false, false, true, false, false],
		[false, false, true, false, false],
		[false, true, true, true, false],
	],
	n: [
		[false, false, false, false, false],
		[false, false, false, false, false],
		[true, false, true, true, false],
		[true, true, false, false, true],
		[true, false, false, false, true],
		[true, false, false, false, true],
		[true, false, false, false, true],
	],
	f: [
		[false, false, true, false, false],
		[false, true, false, true, false],
		[false, true, false, false, false],
		[true, true, true, false, false],
		[false, true, false, false, false],
		[false, true, false, false, false],
		[false, true, false, false, false],
	],
	y: [
		[false, false, false, false, false],
		[false, false, false, false, false],
		[true, false, false, false, true],
		[false, true, false, true, false],
		[false, false, true, false, false],
		[false, false, true, false, false],
		[false, true, false, false, false],
	],
	i: [
		[false, false, true, false, false],
		[false, false, false, false, false],
		[false, true, true, false, false],
		[false, false, true, false, false],
		[false, false, true, false, false],
		[false, false, true, false, false],
		[false, true, true, true, false],
	],
	t: [
		[false, false, false, false, false],
		[false, false, true, false, false],
		[false, true, true, true, false],
		[false, false, true, false, false],
		[false, false, true, false, false],
		[false, false, true, false, true],
		[false, false, false, true, false],
	],
	E: [
		[true, true, true, true, true],
		[true, false, false, false, false],
		[true, false, false, false, false],
		[true, true, true, true, false],
		[true, false, false, false, false],
		[true, false, false, false, false],
		[true, true, true, true, true],
	],
	o: [
		[false, false, false, false, false],
		[false, false, false, false, false],
		[false, true, true, true, false],
		[true, false, false, false, true],
		[true, false, false, false, true],
		[true, false, false, false, true],
		[false, true, true, true, false],
	],
	N: [
		[true, false, false, false, true],
		[true, false, false, false, true],
		[true, true, false, false, true],
		[true, false, true, false, true],
		[true, false, false, true, true],
		[true, false, false, false, true],
		[true, false, false, false, true],
	],
	a: [
		[false, false, false, false, false],
		[false, false, false, false, false],
		[false, true, true, false, false],
		[false, false, false, true, false],
		[false, true, true, true, false],
		[true, false, false, true, false],
		[false, true, true, true, true],
	],
	r: [
		[false, false, false, false, false],
		[false, false, false, false, false],
		[false, true, false, true, true],
		[false, true, true, false, false],
		[false, true, false, false, false],
		[false, true, false, false, false],
		[false, true, false, false, false],
	],
	'(': [
		[false, false, false, true, false],
		[false, false, true, false, false],
		[false, true, false, false, false],
		[false, true, false, false, false],
		[false, true, false, false, false],
		[false, false, true, false, false],
		[false, false, false, true, false],
	],
	')': [
		[false, true, false, false, false],
		[false, false, true, false, false],
		[false, false, false, true, false],
		[false, false, false, true, false],
		[false, false, false, true, false],
		[false, false, true, false, false],
		[false, true, false, false, false],
	],
}

export default displayMappings
