const displayMappings: Record<string, boolean[][]> = {
	'0': [
		[false, true, true, true, false],
		[true, false, false, false, true],
		[true, false, false, true, true],
		[true, false, true, false, true],
		[true, true, false, false, true],
		[true, false, false, false, true],
		[false, true, true, true, false],
	],
	'1': [
		[false, false, true, false, false],
		[false, true, true, false, false],
		[false, false, true, false, false],
		[false, false, true, false, false],
		[false, false, true, false, false],
		[false, false, true, false, false],
		[false, true, true, true, false],
	],
	'2': [
		[false, true, true, true, false],
		[true, false, false, false, true],
		[false, false, false, false, true],
		[false, false, false, true, false],
		[false, false, true, false, false],
		[false, true, false, false, false],
		[true, true, true, true, true],
	],
	'3': [
		[false, true, true, true, false],
		[true, false, false, false, true],
		[false, false, false, false, true],
		[false, false, true, true, false],
		[false, false, false, false, true],
		[true, false, false, false, true],
		[false, true, true, true, false],
	],
	'4': [
		[false, false, false, true, false],
		[false, false, true, true, false],
		[false, true, false, true, false],
		[true, false, false, true, false],
		[true, true, true, true, true],
		[false, false, false, true, false],
		[false, false, false, true, false],
	],
	'5': [
		[true, true, true, true, true],
		[true, false, false, false, false],
		[true, true, true, true, false],
		[false, false, false, false, true],
		[false, false, false, false, true],
		[true, false, false, false, true],
		[false, true, true, true, false],
	],
	'6': [
		[false, true, true, true, false],
		[true, false, false, false, true],
		[true, false, false, false, false],
		[true, true, true, true, false],
		[true, false, false, false, true],
		[true, false, false, false, true],
		[false, true, true, true, false],
	],
	'7': [
		[true, true, true, true, true],
		[false, false, false, false, true],
		[false, false, false, true, false],
		[false, false, true, false, false],
		[false, true, false, false, false],
		[false, true, false, false, false],
		[false, true, false, false, false],
	],
	'8': [
		[false, true, true, true, false],
		[true, false, false, false, true],
		[true, false, false, false, true],
		[false, true, true, true, false],
		[true, false, false, false, true],
		[true, false, false, false, true],
		[false, true, true, true, false],
	],
	'9': [
		[false, true, true, true, false],
		[true, false, false, false, true],
		[true, false, false, false, true],
		[false, true, true, true, true],
		[false, false, false, false, true],
		[true, false, false, false, true],
		[false, true, true, true, false],
	],
	'+': [
		[false, false, false, false, false],
		[false, false, true, false, false],
		[false, false, true, false, false],
		[true, true, true, true, true],
		[false, false, true, false, false],
		[false, false, true, false, false],
		[false, false, false, false, false],
	],
	'-': [
		[false, false, false, false, false],
		[false, false, false, false, false],
		[false, false, false, false, false],
		[true, true, true, true, true],
		[false, false, false, false, false],
		[false, false, false, false, false],
		[false, false, false, false, false],
	],
	'*': [
		[false, false, false, false, false],
		[true, false, false, false, true],
		[false, true, false, true, false],
		[false, false, true, false, false],
		[false, true, false, true, false],
		[true, false, false, false, true],
		[false, false, false, false, false],
	],
	'/': [
		[false, false, false, false, false],
		[false, false, false, false, true],
		[false, false, false, true, false],
		[false, false, true, false, false],
		[false, true, false, false, false],
		[true, false, false, false, false],
		[false, false, false, false, false],
	],
	'.': [
		[false, false, false, false, false],
		[false, false, false, false, false],
		[false, false, false, false, false],
		[false, false, false, false, false],
		[false, false, false, false, false],
		[false, true, true, false, false],
		[false, true, true, false, false],
	],
	e: [
		[false, false, false, false, false],
		[false, false, false, false, false],
		[false, true, true, true, false],
		[true, false, false, false, true],
		[true, true, true, true, false],
		[true, false, false, false, false],
		[false, true, true, true, false],
	],
}

export default displayMappings
